### PR TITLE
toy problem for parallel_objects test

### PR DESCRIPTION
**Pull request by chrishavlin**
this is a very simple sanity check to just make sure the parallel_objects iterator behaves as expected.

### CODE REVIEW

**Comment by chrishavlin** [comment]
the included image with results from my machine

result

**Comment by matthewturk** [comment]
Can you replot actual divided by ideal?

**Comment by chrishavlin** [comment]
result

I also added a bit more info on the test setup (and renamed the relevant file to `test_system_code_info.md`): I included the yt commit hash that these results were run on and the OpenMPI version they ran with (in addition to the initial info I included on my machine). Anything else that might be useful to record? Probably don't need anything for **this** PR, but if we define some more formal test cases to re-run occasionally it'd be good to standardize what info we save.

**Comment by chrishavlin** [comment]
@matthewturk any other suggestions here?

**Comment by matthewturk** [comment]
Nope, I think this works for me.

**Pull request merged**
